### PR TITLE
Osita/texts

### PR DESCRIPTION
**Pull request by ossydimma**

### CODE REVIEW

**Comment by Amospikins** [comment]
**Observations that needs to be fixed**
1. Remove all HTML code .... you have business with only css  (you can locally use html to test your code, but don't push to the online repository)
2. You are suppose to have "light" or "dark" prefix as part of your id or class names in css in order to help us between code responsible for dark and light theme.... for more information, contact the project team leads @Ericademola  and @okhuaroboosayuki . Thanks

**Comment by ossydimma** [comment]
@Amospikins adding the html code wasn't intentional, I actually deleted but forgot to save before pushing.
Coming to the dark and light mode, some of the texts has the same text color  in both modes (light and dark), the ones that have different color I specified it by adding a light mode style under that particular styles ( example: 
 .personal-input-label-txt {
  color: #A9A9A9;
  text-align: center;
  font-family: Poppins;
  font-size: 16px;
  font-weight: 500;
}
.personal-input-label-txt-light-mode {color: #585858;} )

**Comment by Amospikins** [comment]
> @Amospikins adding the html code wasn't intentional, I actually deleted but forgot to save before pushing. Coming to the dark and light mode, some of the texts has the same text color in both modes (light and dark), the ones that have different color I specified it by adding a light mode style under that particular styles ( example: .personal-input-label-txt { color: #A9A9A9; text-align: center; font-family: Poppins; font-size: 16px; font-weight: 500; } .personal-input-label-txt-light-mode {color: #585858;} )

OK!
1. Please delete your html in the splash screen
2. Also put light or dark as prefix at the beginning of your class names e.g. .personal-input-label-txt-light-mode {color: #585858;} ) should be .light-personal-input-label-txt-mode {color: #585858;} )

**Comment by victorsato1** [comment]
Weldone ohh

**Pull request merged**
